CREATE DATABASE BLOG;

USE BLOG;

CREATE TABLE IF NOT EXISTS AUTORES(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(50),
EMAIL VARCHAR(100),
SENHA VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS POSTS(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
TITULO VARCHAR(200),
CONTEUDO TEXT,
AUTOR INT,
FOREIGN KEY (AUTOR) REFERENCES AUTORES (ID)
-- A REFERENCIA DE AUTOR ESTA NA TABELA AUTORES E COLUNA ID, OU SEJA UM AUTOR ESTA ASSOCIADO A UM LOGIN E UM AUTOR PODE TER VARIOS POSTS.
-- TEXT E UM TEXTO COM MUITOS CARACTERES.

-- NESTE EXEMPLO EU COLOQUEI AUTOR MAIS E INTERESANTE COLOCAR ANTES UM FK_
);

-- SELECT * FROM AUTORES;

-- SELECT * FROM POSTS;

-- INSERT INTO POSTS VALUES (null, 'asdsadadsa', 'asdsadadsadsadsadsadsadsadsadsadsadsad', '1');