CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNO
(
NOME VARCHAR(50) NOT NULL,
IDADE INT NOT NULL,
CURSO VARCHAR(80) NOT NULL
)

SELECT * FROM ALUNO;

INSERT INTO ALUNO
VALUES 
("Matheus", 21, "PHP"),
("Beto", 44, "MySQL"),
("Gabriel", 18, "JavaScript"),
("Raul", 32, "Python")
