CREATE DATABASE SISTEMA;

USE SISTEMA;

CREATE TABLE USUARIOS
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(80) NOT NULL, 
-- VARCHAR OU ELE VAI OCUPAR A QUANTIDADE MAXIMA DENTRO DE SEU PARENTESES OU APENAS A QUANTIDADE EM QUE O USUARIO DIGITAR.
-- CHAR ELE VAI SEMPRE OCUPAR A QUANTIDADE DE CARACTERESES DENTRO DE SEU PARENTES INDEPENDETE DO VALOR INSERIDO NELE. (ESPACOS EM BRANCO)
EMAIL VARCHAR(80) NOT NULL UNIQUE,
SENHA CHAR(32) NOT NULL
-- USAMOS CHAR() PARA PODE USAR UMA CRIPTOGRAFIA NO PHP                         
);