CREATE DATABASE SQUAD5;

USE SQUAD5;

CREATE TABLE LOGIN
(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
SENHA VARCHAR(30) NOT NULL
)

select * from login